# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('approval_status', models.BooleanField()),
                ('done_status', models.BooleanField()),
                ('keterangan', models.CharField(blank=True, max_length=300, null=True)),
                ('created_date', models.DateField()),
                ('doing_date', models.DateField()),
                ('approval_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_approval_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
