# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20170420_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_date',
            field=models.DateField(null=True),
        ),
    ]
