# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='update_info',
            field=models.TextField(blank=True),
        ),
    ]
