# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opreport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('inquiry_no', models.CharField(max_length=50)),
                ('quotation_no', models.CharField(max_length=20)),
                ('costumer', models.CharField(max_length=100)),
                ('desc_material', models.TextField()),
                ('qty', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=10)),
                ('bid_price', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
