# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opreport', '0002_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='remark',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
