# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opreport', '0003_project_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('om', models.CharField(choices=[('east', 'East'), ('west', 'West')], max_length=20)),
                ('quotation_no', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('tender_name', models.CharField(max_length=200)),
                ('rks_no', models.CharField(max_length=20)),
                ('process_egistration', models.DateField()),
                ('process_aanwizing', models.DateField()),
                ('process_penbid', models.DateField()),
                ('addcost_bidbond', models.CharField(max_length=100)),
                ('addcost_reffbank', models.CharField(max_length=100)),
                ('addcost_document', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=220)),
            ],
        ),
    ]
