# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opreport', '0005_auto_20170519_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='process_aanwizing',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tender',
            name='process_openbid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tender',
            name='process_registration',
            field=models.CharField(max_length=10),
        ),
    ]
