# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opreport', '0006_auto_20170519_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('om', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('job_no', models.CharField(max_length=200)),
                ('description_material', models.CharField(max_length=200)),
                ('vendor', models.CharField(max_length=200)),
                ('value_dpp', models.CharField(max_length=200)),
                ('value_ppn', models.CharField(max_length=200)),
                ('progress_dono', models.CharField(max_length=200)),
                ('progress_leadtime', models.CharField(max_length=200)),
                ('progress_pickup', models.CharField(max_length=200)),
                ('expedisi', models.CharField(max_length=200)),
                ('order_status', models.CharField(max_length=200)),
            ],
        ),
    ]
