# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opreport', '0009_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='om',
            field=models.CharField(choices=[('east', 'East'), ('west', 'West')], max_length=20),
        ),
    ]
