# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opreport', '0010_auto_20170522_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashadv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_request', models.DateField()),
                ('om', models.CharField(choices=[('east', 'East'), ('west', 'West')], max_length=20)),
                ('name_of_payee', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('id_jobno', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('car', models.CharField(max_length=100)),
                ('pi', models.CharField(max_length=100)),
                ('actual_cost', models.CharField(max_length=100)),
                ('receive_payment', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
