# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opreport', '0013_auto_20170524_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='agustus_budgeting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='agustus_realisasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='april_budgeting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='april_realisasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='desember_budgeting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='desember_realisasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='februari_budgeting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='februari_realisasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='januari_budgeting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='januari_realisasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='juli_budgeting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='juli_realisasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='juni_budgeting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='juni_realisasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='maret_budgeting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='maret_realisasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='mei_budgeting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='mei_realisasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='november_budgeting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='november_realisasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='oktober_budgeting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='oktober_realisasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='september_budgeting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetingrealisasi',
            name='september_realisasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
