# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgeting',
            name='departement',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='budgeting',
            name='divisi',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='budgeting',
            name='jobid',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgeting',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
