# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0003_auto_20170616_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgeting',
            name='disc',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
