# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0005_auto_20170619_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgeting',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='budgeting',
            name='disc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='budgeting',
            name='remark',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='budgeting',
            name='tax',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='budgeting',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, null=True),
        ),
    ]
