# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0011_auto_20170621_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='tot_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
