# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0014_auto_20170621_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
