# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0015_auto_20170703_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='item',
            name='tot_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
