# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.CharField(max_length=200)),
                ('koef', models.IntegerField()),
                ('kode', models.CharField(choices=[('standard', 'Standard'), ('mandatory', 'Mandatory'), ('finance', 'Finance'), ('mandatory_tek', 'Mandatory Teknis')], max_length=100)),
            ],
        ),
    ]
