# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkt', '0002_datas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='data1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='data10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='data11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='data12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='data13',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='data14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='data15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='data16',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='data17',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='data18',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='data19',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='data2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='data20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='data3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='data4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='data5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='data6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='data7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='data8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='data9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
