# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 06:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_myuser_is_atasan'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='atasan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
