# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_myuser_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_staff',
            new_name='is_staf',
        ),
    ]
