# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20170421_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='departement',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='divisi',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='unit',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
